import type { SmashableObjectDef } from '../game/state';

export const OBJECTS: SmashableObjectDef[] = [
  // ── Everyday pack ──────────────────────────────────────────────
  {
    id: 'can',
    name: 'Soda Can',
    pack: 'everyday',
    rarity: 'common',
    color: 0xff4444,
    geometry: 'cylinder',
    scale: [0.6, 1.0, 0.6],
    particleTheme: 'metal',
    category: 'ceramic',
    breakType: 'crackBurst',
    weightClass: 'light',
    spawnWeight: 10,
  },
  {
    id: 'mug',
    name: 'Coffee Mug',
    pack: 'everyday',
    rarity: 'common',
    color: 0xeeeeee,
    geometry: 'cylinder',
    scale: [0.7, 0.8, 0.7],
    particleTheme: 'default',
    category: 'ceramic',
    breakType: 'crackBurst',
    weightClass: 'medium',
    spawnWeight: 10,
  },
  {
    id: 'phone',
    name: 'Phone',
    pack: 'everyday',
    rarity: 'uncommon',
    color: 0x333333,
    geometry: 'box',
    scale: [0.5, 0.9, 0.15],
    particleTheme: 'electronic',
    category: 'tech',
    breakType: 'chunkBreak',
    weightClass: 'light',
    spawnWeight: 5,
  },
  {
    id: 'lamp',
    name: 'Lamp',
    pack: 'everyday',
    rarity: 'uncommon',
    color: 0xffcc00,
    geometry: 'cone',
    scale: [0.7, 1.2, 0.7],
    particleTheme: 'default',
    category: 'ceramic',
    breakType: 'crackBurst',
    weightClass: 'medium',
    spawnWeight: 5,
  },
  {
    id: 'bottle',
    name: 'Glass Bottle',
    pack: 'everyday',
    rarity: 'uncommon',
    color: 0x44bb66,
    geometry: 'cylinder',
    scale: [0.5, 1.1, 0.5],
    particleTheme: 'glass',
    category: 'glass',
    breakType: 'shatter',
    weightClass: 'light',
    spawnWeight: 5,
  },
  {
    id: 'plate',
    name: 'Ceramic Plate',
    pack: 'everyday',
    rarity: 'common',
    color: 0xeeeeee,
    geometry: 'cylinder',
    scale: [0.9, 0.2, 0.9],
    particleTheme: 'glass',
    category: 'ceramic',
    breakType: 'shatter',
    weightClass: 'light',
    spawnWeight: 10,
  },
  {
    id: 'chair',
    name: 'Wooden Chair',
    pack: 'everyday',
    rarity: 'common',
    color: 0x8b5e3c,
    geometry: 'box',
    scale: [0.8, 1.0, 0.8],
    particleTheme: 'default',
    category: 'ceramic',
    breakType: 'chunkBreak',
    weightClass: 'heavy',
    spawnWeight: 10,
  },

  // ── Tech pack ─────────────────────────────────────────────────
  {
    id: 'laptop',
    name: 'Laptop',
    pack: 'weird',
    rarity: 'uncommon',
    color: 0x888888,
    geometry: 'box',
    scale: [0.8, 0.5, 0.6],
    particleTheme: 'electronic',
    category: 'tech',
    breakType: 'chunkBreak',
    weightClass: 'medium',
    spawnWeight: 5,
  },

  {
    id: 'keyboard',
    name: 'Keyboard',
    pack: 'weird',
    rarity: 'common',
    color: 0x333333,
    geometry: 'box',
    scale: [1.0, 0.2, 0.5],
    particleTheme: 'electronic',
    category: 'tech',
    breakType: 'chunkBreak',
    weightClass: 'light',
    spawnWeight: 10,
  },
  {
    id: 'monitor',
    name: 'Monitor',
    pack: 'weird',
    rarity: 'uncommon',
    color: 0x222222,
    geometry: 'box',
    scale: [1.0, 0.8, 0.3],
    particleTheme: 'electronic',
    category: 'tech',
    breakType: 'chunkBreak',
    weightClass: 'heavy',
    spawnWeight: 5,
  },

  // ── Sports pack ────────────────────────────────────────────────
  {
    id: 'football',
    name: 'Football',
    pack: 'sports',
    rarity: 'common',
    color: 0x8b4513,
    geometry: 'sphere',
    scale: [0.7, 0.9, 0.7],
    particleTheme: 'default',
    category: 'soft',
    breakType: 'softBurst',
    weightClass: 'medium',
    spawnWeight: 10,
  },
  {
    id: 'soccer',
    name: 'Soccer Ball',
    pack: 'sports',
    rarity: 'common',
    color: 0xffffff,
    geometry: 'sphere',
    scale: [0.8, 0.8, 0.8],
    particleTheme: 'default',
    category: 'soft',
    breakType: 'softBurst',
    weightClass: 'medium',
    spawnWeight: 10,
  },
  {
    id: 'trophy',
    name: 'Trophy',
    pack: 'sports',
    rarity: 'rare',
    color: 0xffd700,
    geometry: 'cone',
    scale: [0.5, 1.3, 0.5],
    particleTheme: 'metal',
    category: 'luxury',
    breakType: 'premiumBurst',
    weightClass: 'heavy',
    spawnWeight: 1,
  },
  {
    id: 'helmet',
    name: 'Helmet',
    pack: 'sports',
    rarity: 'uncommon',
    color: 0x2244aa,
    geometry: 'sphere',
    scale: [0.9, 0.7, 0.9],
    particleTheme: 'default',
    category: 'ceramic',
    breakType: 'chunkBreak',
    weightClass: 'heavy',
    spawnWeight: 5,
  },

  // ── Weird pack ─────────────────────────────────────────────────
  {
    id: 'duck',
    name: 'Rubber Duck',
    pack: 'weird',
    rarity: 'common',
    color: 0xffdd00,
    geometry: 'sphere',
    scale: [0.7, 0.7, 0.7],
    particleTheme: 'organic',
    category: 'soft',
    breakType: 'softBurst',
    weightClass: 'light',
    spawnWeight: 10,
  },
  {
    id: 'cube-idol',
    name: 'Cube Idol',
    pack: 'weird',
    rarity: 'rare',
    color: 0xff00ff,
    geometry: 'box',
    scale: [0.8, 0.8, 0.8],
    particleTheme: 'electronic',
    category: 'luxury',
    breakType: 'premiumBurst',
    weightClass: 'heavy',
    spawnWeight: 1,
  },
  {
    id: 'tv-head',
    name: 'TV Head',
    pack: 'weird',
    rarity: 'uncommon',
    color: 0x44aaff,
    geometry: 'box',
    scale: [1.0, 0.8, 0.6],
    particleTheme: 'electronic',
    category: 'tech',
    breakType: 'chunkBreak',
    weightClass: 'heavy',
    spawnWeight: 5,
  },
  {
    id: 'statue',
    name: 'Strange Statue',
    pack: 'weird',
    rarity: 'rare',
    color: 0x88ffaa,
    geometry: 'torus',
    scale: [0.9, 0.9, 0.9],
    particleTheme: 'default',
    category: 'ceramic',
    breakType: 'crackBurst',
    weightClass: 'heavy',
    spawnWeight: 1,
  },
  {
    id: 'watermelon',
    name: 'Watermelon',
    pack: 'weird',
    rarity: 'uncommon',
    color: 0x228b22,
    geometry: 'sphere',
    scale: [0.8, 0.7, 0.8],
    particleTheme: 'organic',
    category: 'food',
    breakType: 'juicySplit',
    weightClass: 'medium',
    spawnWeight: 5,
  },

  // ── Meme pack ───────────────────────────────────────────────────
  // Brainrot objects
  {
    id: 'skull',
    name: 'Skull',
    pack: 'meme',
    rarity: 'uncommon',
    color: 0xf5f5dc,
    geometry: 'sphere',
    scale: [0.7, 0.8, 0.7],
    particleTheme: 'default',
    category: 'ceramic',
    breakType: 'crackBurst',
    weightClass: 'medium',
    spawnWeight: 5,
  },
  {
    id: 'brain',
    name: 'Brain',
    pack: 'meme',
    rarity: 'rare',
    color: 0xff8899,
    geometry: 'sphere',
    scale: [0.7, 0.6, 0.7],
    particleTheme: 'organic',
    category: 'food',
    breakType: 'juicySplit',
    weightClass: 'medium',
    spawnWeight: 1,
  },

  {
    id: 'weird-face',
    name: 'Weird Face',
    pack: 'meme',
    rarity: 'rare',
    color: 0xcc8855,
    geometry: 'sphere',
    scale: [0.8, 0.9, 0.8],
    particleTheme: 'organic',
    category: 'soft',
    breakType: 'softBurst',
    weightClass: 'medium',
    spawnWeight: 1,
  },

  {
    id: 'blob',
    name: 'Distorted Blob',
    pack: 'meme',
    rarity: 'rare',
    color: 0x66ff99,
    geometry: 'sphere',
    scale: [0.8, 0.8, 0.8],
    particleTheme: 'organic',
    category: 'soft',
    breakType: 'softBurst',
    weightClass: 'heavy',
    spawnWeight: 1,
  },

  // Chaos objects
  {
    id: 'banana',
    name: 'Banana',
    pack: 'meme',
    rarity: 'uncommon',
    color: 0xffe135,
    geometry: 'cylinder',
    scale: [0.4, 1.0, 0.4],
    particleTheme: 'organic',
    category: 'food',
    breakType: 'juicySplit',
    weightClass: 'light',
    spawnWeight: 5,
  },
  {
    id: 'rubber-chicken',
    name: 'Rubber Chicken',
    pack: 'meme',
    rarity: 'uncommon',
    color: 0xffcc00,
    geometry: 'cylinder',
    scale: [0.5, 1.1, 0.5],
    particleTheme: 'organic',
    category: 'soft',
    breakType: 'softBurst',
    weightClass: 'light',
    spawnWeight: 5,
  },
  {
    id: 'toilet',
    name: 'Toilet',
    pack: 'meme',
    rarity: 'uncommon',
    color: 0xffffff,
    geometry: 'cylinder',
    scale: [0.8, 0.9, 0.8],
    particleTheme: 'glass',
    category: 'ceramic',
    breakType: 'crackBurst',
    weightClass: 'heavy',
    spawnWeight: 5,
  },
  {
    id: 'traffic-cone',
    name: 'Traffic Cone',
    pack: 'meme',
    rarity: 'uncommon',
    color: 0xff6600,
    geometry: 'cone',
    scale: [0.6, 1.2, 0.6],
    particleTheme: 'default',
    category: 'ceramic',
    breakType: 'chunkBreak',
    weightClass: 'medium',
    spawnWeight: 5,
  },

  // Gamer objects
  {
    id: 'controller',
    name: 'Game Controller',
    pack: 'meme',
    rarity: 'uncommon',
    color: 0x222222,
    geometry: 'box',
    scale: [0.8, 0.4, 0.5],
    particleTheme: 'electronic',
    category: 'tech',
    breakType: 'chunkBreak',
    weightClass: 'light',
    spawnWeight: 5,
  },
  {
    id: 'headset',
    name: 'Gaming Headset',
    pack: 'meme',
    rarity: 'rare',
    color: 0x111111,
    geometry: 'torus',
    scale: [0.8, 0.8, 0.5],
    particleTheme: 'electronic',
    category: 'tech',
    breakType: 'chunkBreak',
    weightClass: 'medium',
    spawnWeight: 1,
  },

  // Special rare meme objects
  {
    id: 'golden-toilet',
    name: 'Golden Toilet',
    pack: 'meme',
    rarity: 'rare',
    color: 0xffd700,
    geometry: 'cylinder',
    scale: [0.8, 0.9, 0.8],
    particleTheme: 'metal',
    category: 'luxury',
    breakType: 'premiumBurst',
    weightClass: 'heavy',
    spawnWeight: 1,
  },
];
