import type { SmashableObjectDef } from '../game/state';

export const OBJECTS: SmashableObjectDef[] = [
  // ── Everyday pack ──────────────────────────────────────────────
  {
    id: 'can',
    name: 'Soda Can',
    pack: 'everyday',
    rarity: 'common',
    color: 0xff4444,
    geometry: 'cylinder',
    scale: [0.6, 1.0, 0.6],
    particleTheme: 'metal',
  },
  {
    id: 'mug',
    name: 'Coffee Mug',
    pack: 'everyday',
    rarity: 'common',
    color: 0xeeeeee,
    geometry: 'cylinder',
    scale: [0.7, 0.8, 0.7],
    particleTheme: 'default',
  },
  {
    id: 'phone',
    name: 'Phone',
    pack: 'everyday',
    rarity: 'uncommon',
    color: 0x333333,
    geometry: 'box',
    scale: [0.5, 0.9, 0.15],
    particleTheme: 'electronic',
  },
  {
    id: 'lamp',
    name: 'Lamp',
    pack: 'everyday',
    rarity: 'uncommon',
    color: 0xffcc00,
    geometry: 'cone',
    scale: [0.7, 1.2, 0.7],
    particleTheme: 'default',
  },
  {
    id: 'bottle',
    name: 'Glass Bottle',
    pack: 'everyday',
    rarity: 'uncommon',
    color: 0x44bb66,
    geometry: 'cylinder',
    scale: [0.5, 1.1, 0.5],
    particleTheme: 'glass',
  },

  // ── Sports pack ────────────────────────────────────────────────
  {
    id: 'football',
    name: 'Football',
    pack: 'sports',
    rarity: 'common',
    color: 0x8b4513,
    geometry: 'sphere',
    scale: [0.7, 0.9, 0.7],
    particleTheme: 'default',
  },
  {
    id: 'soccer',
    name: 'Soccer Ball',
    pack: 'sports',
    rarity: 'common',
    color: 0xffffff,
    geometry: 'sphere',
    scale: [0.8, 0.8, 0.8],
    particleTheme: 'default',
  },
  {
    id: 'trophy',
    name: 'Trophy',
    pack: 'sports',
    rarity: 'rare',
    color: 0xffd700,
    geometry: 'cone',
    scale: [0.5, 1.3, 0.5],
    particleTheme: 'metal',
  },
  {
    id: 'helmet',
    name: 'Helmet',
    pack: 'sports',
    rarity: 'uncommon',
    color: 0x2244aa,
    geometry: 'sphere',
    scale: [0.9, 0.7, 0.9],
    particleTheme: 'default',
  },

  // ── Weird pack ─────────────────────────────────────────────────
  {
    id: 'duck',
    name: 'Rubber Duck',
    pack: 'weird',
    rarity: 'common',
    color: 0xffdd00,
    geometry: 'sphere',
    scale: [0.7, 0.7, 0.7],
    particleTheme: 'organic',
  },
  {
    id: 'cube-idol',
    name: 'Cube Idol',
    pack: 'weird',
    rarity: 'rare',
    color: 0xff00ff,
    geometry: 'box',
    scale: [0.8, 0.8, 0.8],
    particleTheme: 'electronic',
  },
  {
    id: 'tv-head',
    name: 'TV Head',
    pack: 'weird',
    rarity: 'uncommon',
    color: 0x44aaff,
    geometry: 'box',
    scale: [1.0, 0.8, 0.6],
    particleTheme: 'electronic',
  },
  {
    id: 'statue',
    name: 'Strange Statue',
    pack: 'weird',
    rarity: 'rare',
    color: 0x88ffaa,
    geometry: 'torus',
    scale: [0.9, 0.9, 0.9],
    particleTheme: 'default',
  },
  {
    id: 'watermelon',
    name: 'Watermelon',
    pack: 'weird',
    rarity: 'uncommon',
    color: 0x228b22,
    geometry: 'sphere',
    scale: [0.8, 0.7, 0.8],
    particleTheme: 'organic',
  },
];
